server:
  port: 8080
  tomcat:
    connection-timeout: 30s # 30초 (클라이언트 타임아웃인 15초보다 길게)

payment:
  url: ${PAYMENT_URL:http://localhost:8081}

spring:
  application:
    name: fcfs-ticket
  datasource:
    url: jdbc:mysql://mysql:3306/fcfs_ticket
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000 # 30초
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.validation: DEBUG
    com.example: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
